---
- name: configuring tomcat
  hosts: all
  tasks:
    - name: install tomcat10
      apt: 
       name: tomcat10
       state: present
       update_cache: yes
    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: change port of the tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: pause for 30 sec
      pause: 
       seconds: 30
    - name: check tomcat on server 1
      uri: 
       url: http://172.31.6.115
       status_code: 200
    - name: check tomcat on server 2
      uri:
       url: http://172.31.5.77
       status_code: 200


